name:                nanovg-simple
version:             0.5.0.0
github:              "CthulhuDen/nanovg-simple"
license:             BSD3
author:              "Cthulhu"
maintainer:          "cthulhu.den@gmail.com"
copyright:           "Cthulhu (c) 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple interface to rendering with NanoVG
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CthulhuDen/nanovg-simple#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  c-sources:             cbits/glew.c
  exposed-modules:
  - Graphics.NanoVG.Simple
  - Graphics.NanoVG.Picture
  dependencies:
  - nanovg >= 0.6.0.0 && < 0.7
  - GLFW-b >= 3.2.1.0 && < 3.4
  - OpenGL >= 3.0.2.2 && < 3.1
  - text >= 1.2.3.0 && < 1.3
  - monad-loops >= 0.4.3 && < 0.5
  - safe-exceptions >= 0.1.7.0 && < 0.2

ghc-options:
- -Wall

executables:
  nanovg-simple:
    when:
    - condition: flag(library-only)
      buildable: false
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    dependencies:
    - nanovg-simple
    - nanovg >= 0.6.0.0 && < 0.7
    - time >= 1.8.0.2 && < 1.10

flags:
  library-only:
    default: true
    manual: false
